image: archlinux
packages:
  - lowdown
  - cpio
  - hut
oauth: pages.sr.ht/PAGES:RW
environment:
  site: wculhane.com
tasks:
- package: |
    cd $site
    make site.tar.gz
- upload: |
    hut pages publish -d $site $site/site.tar.gz
